//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int idorder { get; set; }
        public Nullable<int> idbasket { get; set; }
        public Nullable<int> iduser { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> orderstatus { get; set; }
    
        public virtual basket basket { get; set; }
        public virtual users users { get; set; }
    }
}
